import axios from "axios";

/**
 * Returns a Promise generated by an axios post request.
 *
 * @param {object} character Character to get equipment data for
 * @param {string} character.realm Character realm
 * @param {string} character.name Character name
 * @return {Promise}
 */
export default function equipmentRequest(character) {
  return axios({
    method: "post",
    url: process.env.VUE_APP_WOWQL_URL,
    withCredentials: true,
    data: {
      query: `{
				characterEquipment(realm: "${character.realm}", name: "${character.name}") {
					character {
						name
					}
					equipped_items {
						item {
							id
						}
						slot {
							type
							name
						}
						name
						azerite_details {
							percentage_to_next_level
							level {
								value
							}
						}
						level {
							value
						}
						armor {
							value
						}
						stats {
							type {
								type
								name
							}
							value
							is_negated
						} 
					}
				}
			}`
    }
  });
}
