import axios from "axios";

/**
 * Returns a Promise generated by an axios post request.
 *
 * @param {object} character Character to get media data for
 * @param {string} character.realm Character realm
 * @param {string} character.name Character name
 * @return {Promise}
 */
export default function mediaRequest(character) {
  return axios({
    method: "post",
    url: process.env.VUE_APP_WOWQL_URL,
    withCredentials: true,
    data: {
      query: `{
				characterMedia(realm: "${character.realm}", name: "${character.name}") {
          character {
            name
          }
          avatar_url
				}
			}`
    }
  });
}
