import axios from "axios";

/**
 * Returns a Promise generated by an axios post request.
 *
 * @param {object} character Character to get profile data for
 * @param {string} character.realm Character realm
 * @param {string} character.name Character name
 * @return {Promise}
 */
export default function profileRequest(character) {
  return axios({
    method: "post",
    url: process.env.VUE_APP_WOWQL_URL,
    withCredentials: true,
    data: {
      query: `{
				characterProfile(realm: "${character.realm}", name: "${character.name}") {
					name
          level
          average_item_level
				}
			}`
    }
  });
}
